catalog/urls.py
from django.urls import path

from .apps import CatalogConfig
from .views import MainListView, ProductsListView, CategoriesListView, CategoryProductsListView, ProductDetailView
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    #FBV path('', index, name='index'),
    path('', MainListView.as_view(), name='index'),
    #FBV path('categories/', categories, name='categories'),
    path('categories/', CategoriesListView.as_view(), name='categories'),
    #FBV path('<int:pk>/products/', category_products, name='category_products'),
    path('<int:pk>/products/', CategoryProductsListView.as_view(), name='category_products'),
    #FBV path('productsall/', products, name='products'),
    path('productsall/', ProductsListView.as_view(), name='products'),
    #FBV path('<int:pk>/product/', product_detailed, name='product_detailed'),
    path('<int:pk>/product/', ProductDetailView.as_view(), name='product_detailed'),
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('<int:pk>/blog/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/blog/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/blog/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

homework_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    # created_at = models.DateTimeField(verbose_name='Дата создания')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    picture = models.ImageField(**NULLABLE, upload_to='product/', verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    data_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    data_edit = models.DateTimeField(**NULLABLE, verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name', 'data_create',)


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(**NULLABLE, max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(**NULLABLE, upload_to='blog/', verbose_name='Превью')
    data_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('title',)

catalog/views.py
from django.shortcuts import render
from catalog.models import Category, Product, Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

# Create your views here.

# FBV подход
# def index(request):
# '''контроллер главной страницы'''
# context = {
# 'object_list': Product.objects.all(),
# 'title': 'Онлайн магазин',
# 'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'
# }
# return render(request, 'catalog/index.html', context)


'''CBV подход'''

class MainListView(ListView):
    '''Контролер главной страницы. Отображает все товары без категорий'''
    model = Product
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Выбираем нужный товар.'
    }


# FBV подход
# def categories(request):
# '''контроллер страницы всех категорий'''
# context = {
#   'object_list': Category.objects.all(),
#  'title': 'Онлайн магазин',
#   'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'

# }
# return render(request, 'catalog/categories.html', context)


'''CBV подход'''

class CategoriesListView(ListView):
    '''Контроллер страницы Категории'''
    model = Category
    template_name = 'catalog/categories.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'
    }


# FBV подход
# def category_products(request, pk):
# '''контроллер страницы всех товаров с категориями'''
# category_item = Category.objects.get(pk=pk)
# context = {
#    'object_list': Product.objects.filter(category_id=pk),
#    'title': f'Товары из {category_item.name}',
#    'title_text': 'Добро пожаловать! Выбираем нужный Вам товар.'

# }
# return render(request, 'catalog/products.html', context)


'''CBV подход'''

class CategoryProductsListView(ListView):
    '''Контроллер страницы товаров в конкретной Категории'''
    model = Product
    template_name = 'catalog/products.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk,
        context_data['title'] = f'Товары из {category_item.name}'
        context_data['title_text'] = f'Добро пожаловать! Выбираем нужный Вам товар.'

        return context_data


# FBV подход
# def products(request):
# '''контроллер страницы всех товаров без категорий'''
# products_list = Product.objects.all()
# context = {
#    'object_list': products_list
# }
# return render(request, "catalog/products_all.html", context)


'''CBV подход'''

class ProductsListView(ListView):
    '''Контролер страницы Товары. Отображает все товары без категорий'''
    model = Product
    template_name = 'catalog/products_all.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Ознакомьтесь с товарами.'
    }


# FBV подход
# def product_detailed(request, pk):
# '''контроллер страницы одного товара'''
# category_item = Product.objects.get(pk=pk)
# context = {
#    'object_list': Product.objects.filter(pk=pk),
#    'title': f'Товар - {category_item.name}',
#    'title_text': 'Добро пожаловать! Выбираем нужный Вам товар.',
#    'name_card': category_item.name,
#    'price': category_item.price,
#    'description': category_item.description,
#    'data_added': category_item.data_create,
#    'data_edit': category_item.data_edit

# }
# return render(request, "catalog/product_detail.html", context)


'''CBV подход'''

class ProductDetailView(DetailView):
    '''Контроллер страницы одного товара'''
    model = Product
    template_name = 'catalog/product_detail.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Ознакомьтесь с товаром.'
    }


'''Форма Blog'''


class BlogCreateView(CreateView):
    '''CREATE - создается запись'''
    model = Blog
    fields = ('title', 'slug', 'body', 'preview', 'data_create', 'is_published', 'views_count',)
    success_url = reverse_lazy('catalog:blog_index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    '''READ - чтение списка записей'''
    model = Blog
    template_name = 'catalog/blog_index.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    '''READ - чтение одной записи'''
    model = Blog
    success_url = reverse_lazy('catalog:blog_detail')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    '''UPDATE - обновление записи'''
    model = Blog
    fields = ('title', 'slug', 'body', 'preview', 'data_create', 'is_published', 'views_count',)
    success_url = reverse_lazy('catalog:blog_index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
            self.kwargs['slug'] = new_mat.slug

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    '''DELETE - удаление записи'''
    model = Blog
    success_url = reverse_lazy('catalog:blog_index')

templates/catalog/includes/inc_all_products.html
{% load my_tags %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">

                        <img class="card-img-top"
                                 alt="Card image cap"
                            {#   src="/media/{{ object.picture }}"#}
                                src="{{ object.picture|mediapath }}"
                        >

                        <ul class="list-unstyled mt-3 mb-4">

                            {{ object.description|truncatechars:100 }}
                                <li>Примечание: карточки всех товаров</li>

                        </ul>
                    <a href="{% url 'catalog:product_detailed' object.pk %}" type="button" class="w-100 btn btn-lg btn-primary">Подробнее о товаре</a>

                    </div>
                </div>

            </div>

templates/catalog/includes/inc_category.html
<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm border-primary">
        <div class="card-header py-3 text-bg-primary border-primary">
            <h4 class="my-0 fw-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                {{ object.description|truncatechars:100 }}
                <li>Категории</li>
            </ul>
            <a href="{% url 'catalog:category_products' object.pk %}" type="button" class="w-100 btn btn-lg btn-primary">Перейти к товарам</a>
        </div>

    </div>

</div>

templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Меню</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:index' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:categories' %}">Категории</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:products' %}">Товары</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:blog_index' %}">Блог</a>

    </nav>

    </div>