catalog/urls.py
from django.urls import path

from .apps import CatalogConfig
from .views import MainListView, ProductsListView, CategoriesListView, CategoryProductsListView, ProductDetailView
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    #FBV path('', index, name='index'),
    path('', MainListView.as_view(), name='index'),
    #FBV path('categories/', categories, name='categories'),
    path('categories/', CategoriesListView.as_view(), name='categories'),
    #FBV path('<int:pk>/products/', category_products, name='category_products'),
    path('<int:pk>/products/', CategoryProductsListView.as_view(), name='category_products'),
    #FBV path('productsall/', products, name='products'),
    path('productsall/', ProductsListView.as_view(), name='products'),
    #FBV path('<int:pk>/product/', product_detailed, name='product_detailed'),
    path('<int:pk>/product/', ProductDetailView.as_view(), name='product_detailed'),
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('<int:pk>/blog/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/blog/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/blog/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

homework_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    # created_at = models.DateTimeField(verbose_name='Дата создания')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    picture = models.ImageField(**NULLABLE, upload_to='product/', verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    data_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    data_edit = models.DateTimeField(**NULLABLE, verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name', 'data_create',)


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(**NULLABLE, max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(**NULLABLE, upload_to='blog/', verbose_name='Превью')
    data_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('title',)

catalog/views.py
from django.shortcuts import render
from catalog.models import Category, Product, Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

# Create your views here.

# FBV подход
# def index(request):
# '''контроллер главной страницы'''
# context = {
# 'object_list': Product.objects.all(),
# 'title': 'Онлайн магазин',
# 'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'
# }
# return render(request, 'catalog/index.html', context)


'''CBV подход'''

class MainListView(ListView):
    '''Контролер главной страницы. Отображает все товары без категорий'''
    model = Product
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Выбираем нужный товар.'
    }


# FBV подход
# def categories(request):
# '''контроллер страницы всех категорий'''
# context = {
#   'object_list': Category.objects.all(),
#  'title': 'Онлайн магазин',
#   'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'

# }
# return render(request, 'catalog/categories.html', context)


'''CBV подход'''

class CategoriesListView(ListView):
    '''Контроллер страницы Категории'''
    model = Category
    template_name = 'catalog/categories.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Выбираем нужную Вам категорию товаров.'
    }


# FBV подход
# def category_products(request, pk):
# '''контроллер страницы всех товаров с категориями'''
# category_item = Category.objects.get(pk=pk)
# context = {
#    'object_list': Product.objects.filter(category_id=pk),
#    'title': f'Товары из {category_item.name}',
#    'title_text': 'Добро пожаловать! Выбираем нужный Вам товар.'

# }
# return render(request, 'catalog/products.html', context)


'''CBV подход'''

class CategoryProductsListView(ListView):
    '''Контроллер страницы товаров в конкретной Категории'''
    model = Product
    template_name = 'catalog/products.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk,
        context_data['title'] = f'Товары из {category_item.name}'
        context_data['title_text'] = f'Добро пожаловать! Выбираем нужный Вам товар.'

        return context_data


# FBV подход
# def products(request):
# '''контроллер страницы всех товаров без категорий'''
# products_list = Product.objects.all()
# context = {
#    'object_list': products_list
# }
# return render(request, "catalog/products_all.html", context)


'''CBV подход'''

class ProductsListView(ListView):
    '''Контролер страницы Товары. Отображает все товары без категорий'''
    model = Product
    template_name = 'catalog/products_all.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Ознакомьтесь с товарами.'
    }


# FBV подход
# def product_detailed(request, pk):
# '''контроллер страницы одного товара'''
# category_item = Product.objects.get(pk=pk)
# context = {
#    'object_list': Product.objects.filter(pk=pk),
#    'title': f'Товар - {category_item.name}',
#    'title_text': 'Добро пожаловать! Выбираем нужный Вам товар.',
#    'name_card': category_item.name,
#    'price': category_item.price,
#    'description': category_item.description,
#    'data_added': category_item.data_create,
#    'data_edit': category_item.data_edit

# }
# return render(request, "catalog/product_detail.html", context)


'''CBV подход'''

class ProductDetailView(DetailView):
    '''Контроллер страницы одного товара'''
    model = Product
    template_name = 'catalog/product_detail.html'
    extra_context = {
        'title': 'Онлайн магазин',
        'title_text': 'Добро пожаловать! Ознакомьтесь с товаром.'
    }


'''Форма Blog'''


class BlogCreateView(CreateView):
    '''CREATE - создается запись'''
    model = Blog
    fields = ('title', 'slug', 'body', 'preview', 'data_create', 'is_published', 'views_count',)
    success_url = reverse_lazy('catalog:blog_index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    '''READ - чтение списка записей'''
    model = Blog
    template_name = 'catalog/blog_index.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    '''READ - чтение одной записи'''
    model = Blog
    success_url = reverse_lazy('catalog:blog_detail')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    '''UPDATE - обновление записи'''
    model = Blog
    fields = ('title', 'slug', 'body', 'preview', 'data_create', 'is_published', 'views_count',)
    success_url = reverse_lazy('catalog:blog_index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
            self.kwargs['slug'] = new_mat.slug

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    '''DELETE - удаление записи'''
    model = Blog
    success_url = reverse_lazy('catalog:blog_index')

templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>Online Shop</title>





<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Favicons -->

<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>

    {% include 'catalog/includes/inc_menu.html' %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">{{ title }}</h1>
      <p class="fs-5 text-body-secondary">{{ title_text }}</p>
    </div>

  </header>

  <main>

      {% block content %}
      {% endblock %}




  </main>


  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">

        <small class="d-block mb-3 text-body-secondary">&copy; 2020 - {% now 'Y' %}</small>
      </div>


    </div>

  </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    </body>
</html>

templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<form method="post">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        Удаление поста
                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            <p>Вы действительно хотите удалить запись - {{ object.title }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                Удалить
                            </button>
                            <a class="btn btn-outline-warning" href="{% url 'catalog:blog_index' %}">Отмена</a>

                    </div>
                </div>
            </div>

</form>


      {% endblock %}

templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">

                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal text-center">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">


                        <p class="card-text">Описание: {{ object.body|truncatechars:100 }}</p>
                        <p class="card-text">Дата создания: {{ object.data_create }}</p>
                        <p class="card-text">Дата редактирования: {{ object.is_published}}</p>
                        <p class="card-text">Количество просмотров: {{ object.views_count}}</p>


                        <ul class="list-unstyled mt-3 mb-4">

                                <li><p class="fw-bold">Примечание: карточка одного блога</p></li>
                        </ul>

                        <button type="button" class="btn btn-lg btn-block btn-outline-primary" ><a href="{% url 'catalog:blog_update' object.pk %}" style="text-decoration: none;">Редактировать пост</a></button>
                        <button type="button" class="btn btn-lg btn-block btn-outline-danger float-right" ><a href="{% url 'catalog:blog_delete' object.pk %}" style="text-decoration: none;">Удалить пост</a></button>


                    </div>
                </div>


            </div>




      {% endblock %}

templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        {% if object %}
                            Редактирование
                        {% else %}
                            Добавление
                        {% endif %}

                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>

                    </div>
                </div>
            </div>

</form>


      {% endblock %}

templates/catalog/blog_index.html
{% extends 'catalog/base.html' %}
{% block content %}


    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

        <div class="col-12 mb-5">
        <a href="{% url 'catalog:blog_create' %}" class="btn btn-primary">Создать пост</a>
        </div>

        {% for object in object_list %}

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">

                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">
                        <p>{{ object.body|truncatechars:100 }}</p>

                        <ul class="list-unstyled mt-3 mb-4">
                            <li>- Создан: {{ object.data_create }}</li>
                            <li>- Просмотров: {{ object.views_count }}</li>
                            </ul>
                        <a href="{% url 'catalog:blog_detail' object.pk %}" type="button" class="w-100 btn btn-lg btn-primary">Подробнее</a>
                    </div>

                </div>

            </div>


        {% endfor %}



    </div>


      {% endblock %}

templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}


    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}

            {% include 'catalog/includes/inc_category.html' %}

        {% endfor %}


    </div>



      {% endblock %}

templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}


    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}

            {% include 'catalog/includes/inc_all_products.html' %}

        {% endfor %}



    </div>



      {% endblock %}

templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">

                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal text-center">{{ object.name|title }}</h4>
                    </div>

                    <div class="card-body">

                        <img class="card-img-top"
                                 alt="Card image cap"
                            {#   src="/media/{{ object.picture }}"#}
                                src="{{ object.picture|mediapath }}"
                        >

                        <p class="card-text">Описание: {{ object.description|truncatechars:100 }}</p>
                        <p class="card-text">Цена: {{ object.price }}</p>
                        <p class="card-text">Дата создания: {{ object.data_create }}</p>
                        <p class="card-text">Дата редактирования: {{ object.data_edit }}</p>


                        <ul class="list-unstyled mt-3 mb-4">

                                <li><p class="fw-bold">Примечание: карточка одного товара</p></li>
                        </ul>


                    </div>
                </div>

            </div>




      {% endblock %}

templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">

                        <img class="card-img-top"
                                 alt="Card image cap"
                            {#   src="/media/{{ object.picture }}"#}
                                src="/media/{{ object.picture|mediapath }}"
                        >

                        <ul class="list-unstyled mt-3 mb-4">

                            <p>{% if el.content|length <= 100 %}
                                {{ object.description }}
                                <li>Some test text</li>
                            {% else %}
                                <li>{{ el.content|slice:":100" }}...</li>

                            {% endif %}

                        </ul>

                    </div>
                </div>
            </div>

        {% endfor %}



    </div>



      {% endblock %}

templates/catalog/products_all.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">

                        <img class="card-img-top"
                                 alt="Card image cap"
                            {#   src="/media/{{ object.picture }}"#}
                                src="{{ object.picture|mediapath }}"
                        >

                        <ul class="list-unstyled mt-3 mb-4">

                            {{ object.description|truncatechars:100 }}
                                <li>Примечание: карточки всех товаров</li>

                        </ul>
                    <a href="{% url 'catalog:product_detailed' object.pk %}" type="button" class="w-100 btn btn-lg btn-primary">Подробнее о товаре</a>

                    </div>
                </div>

            </div>


        {% endfor %}



    </div>





      {% endblock %}